output_sink: elasticsearch
output_index: health-plans

# Basic configuration for Elastic Crawler

elasticsearch:
  host: https://centene-serverless-demo-a038f2.es.us-east-1.aws.elastic.cloud
  port: 443
  api_key: Z2t5cDdwa0JWVEtzRW5CbkhjbDc6c05ReVZ4NFZIQVdyYnppNlB3V1NxUQ==
  pipeline_enabled: false


domains:
  - url: https://www.ambetterhealth.com
    seed_urls:
      - https://www.ambetterhealth.com/en/tx/2025-brochures-epo/
    crawl_rules:
      # allow the main brochures page and pagination
      - policy: allow
        type: begins
        pattern: /en/tx/2025-brochures-epo/
      # allow pagination links (page=2, page=3, etc.)
      - policy: allow
        type: regex
        pattern: /en/tx/2025-brochures-epo/\?page=\d+
      # allow any sub-paths under the brochures section
      - policy: allow
        type: begins
        pattern: /en/tx/2025-brochures-epo/
      # deny everything else in domain to avoid crawling full site
      - policy: deny
        type: regex
        pattern: .*
    # Enable content extraction for better link discovery
    content_extraction:
      enabled: true

  - url: https://api.centene.com
    seed_urls:
      - https://api.centene.com/Brochures/2025/29418PremierTX.pdf
      - https://api.centene.com/EOC/2025/29418TX014.pdf
      - https://api.centene.com/EOC/2025/29418TX016.pdf
      - https://api.centene.com/EOC/2025/29418TX017.pdf
      - https://api.centene.com/OOC/2025/29418TX014-OC.pdf
      - https://api.centene.com/OOC/2025/29418TX017-OC.pdf
    crawl_rules:
      # allow PDF files from centene API
      - policy: allow
        type: regex
        pattern: .*\.pdf$
      # deny everything else
      - policy: deny
        type: regex
        pattern: .*
    # enable binary extraction if PDFs are present 
    content_extraction:
      enabled: true
      mime_types:
        - "application/pdf"




