output_sink: elasticsearch
output_index: health-plans

elasticsearch:
  host: https://centene-serverless-demo-a038f2.es.us-east-1.aws.elastic.cloud
  port: 443
  api_key: Z2t5cDdwa0JWVEtzRW5CbkhjbDc6c05ReVZ4NFZIQVdyYnppNlB3V1NxUQ==
  pipeline_enabled: false

domains:
  - url: https://api.centene.com
    seed_urls:
      - https://api.centene.com/Brochures/2025/29418PremierTX.pdf
    crawl_rules:
      # allow PDF files from centene API
      - policy: allow
        type: regex
        pattern: .*\.pdf$
      # deny everything else
      - policy: deny
        type: regex
        pattern: .*
    # enable binary extraction if PDFs are present 
    content_extraction:
      enabled: true
      mime_types:
        - "application/pdf"
